# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_docs_parkedcall_get import ServiceDocsParkedcallGet

class TestServiceDocsParkedcallGet(unittest.TestCase):
    """ServiceDocsParkedcallGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceDocsParkedcallGet:
        """Test ServiceDocsParkedcallGet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceDocsParkedcallGet`
        """
        model = ServiceDocsParkedcallGet()
        if include_optional:
            return ServiceDocsParkedcallGet(
                data = [
                    {
                        'key' : openapi_client.models.service/parking_slot_data.service.ParkingSlotData(
                            attended = True, 
                            call_id = '', 
                            cid_name = '', 
                            cid_number = '', 
                            cid_uri = '', 
                            from_tag = '', 
                            node = '', 
                            presence_id = '', 
                            presence_realm = '', 
                            presence_type = '', 
                            presence_user = '', 
                            ringback_id = '', 
                            slot_call_id = '', 
                            switch_uri = '', 
                            to_tag = '', )
                        }
                    ],
                next_start_key = '',
                page_size = 56,
                request_id = '',
                start_key = '',
                status_code = 56
            )
        else:
            return ServiceDocsParkedcallGet(
        )
        """

    def testServiceDocsParkedcallGet(self):
        """Test ServiceDocsParkedcallGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
