# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_docs_event_detail import ServiceDocsEventDetail

class TestServiceDocsEventDetail(unittest.TestCase):
    """ServiceDocsEventDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceDocsEventDetail:
        """Test ServiceDocsEventDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceDocsEventDetail`
        """
        model = ServiceDocsEventDetail()
        if include_optional:
            return ServiceDocsEventDetail(
                data = [
                    openapi_client.models.model/event_detail.model.EventDetail(
                        account_id = '', 
                        component = '', 
                        created_at = '', 
                        event_name = '', 
                        exec_status = '', 
                        log_date = '', 
                        log_time = '', 
                        username = '', )
                    ],
                next_start_key = '',
                page_size = 56,
                request_id = '',
                start_key = '',
                status_code = 56
            )
        else:
            return ServiceDocsEventDetail(
        )
        """

    def testServiceDocsEventDetail(self):
        """Test ServiceDocsEventDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
