# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.models_account_output_full import ModelsAccountOutputFull

class TestModelsAccountOutputFull(unittest.TestCase):
    """ModelsAccountOutputFull unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelsAccountOutputFull:
        """Test ModelsAccountOutputFull
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelsAccountOutputFull`
        """
        model = ModelsAccountOutputFull()
        if include_optional:
            return ModelsAccountOutputFull(
                caller_id = openapi_client.models.models/voip_account_output_full_callerid.models.VOIPAccountOutputFullCallerid(
                    emergency = openapi_client.models.models/account_output_full_callerid_emergency.models.AccountOutputFullCalleridEmergency(
                        number = '', ), 
                    external = openapi_client.models.models/account_output_full_callerid_external.models.AccountOutputFullCalleridExternal(
                        number = '', ), 
                    internal = openapi_client.models.models/account_output_full_callerid_internal.models.AccountOutputFullCalleridInternal(
                        number = '', ), ),
                do_not_disturb = openapi_client.models.models/voip_shared_do_not_disturb.models.VOIPSharedDoNotDisturb(
                    enabled = True, ),
                enabled = True,
                id = '',
                music_on_hold = openapi_client.models.models/voip_account_music_on_hold.models.VOIPAccountMusicOnHold(
                    media_id = '', ),
                name = '',
                realm = '',
                timezone = ''
            )
        else:
            return ModelsAccountOutputFull(
        )
        """

    def testModelsAccountOutputFull(self):
        """Test ModelsAccountOutputFull"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
