# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.metaflow_api import MetaflowApi


class TestMetaflowApi(unittest.TestCase):
    """MetaflowApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetaflowApi()

    def tearDown(self) -> None:
        pass

    def test_v1_account_account_id_device_device_id_metaflow_delete(self) -> None:
        """Test case for v1_account_account_id_device_device_id_metaflow_delete

        Delete Device Metaflow
        """
        pass

    def test_v1_account_account_id_device_device_id_metaflow_get(self) -> None:
        """Test case for v1_account_account_id_device_device_id_metaflow_get

        Get Device Metaflow List
        """
        pass

    def test_v1_account_account_id_device_device_id_metaflow_post(self) -> None:
        """Test case for v1_account_account_id_device_device_id_metaflow_post

        Create Device Metaflow
        """
        pass

    def test_v1_account_account_id_metaflow_delete(self) -> None:
        """Test case for v1_account_account_id_metaflow_delete

        Delete Account Metaflow
        """
        pass

    def test_v1_account_account_id_metaflow_get(self) -> None:
        """Test case for v1_account_account_id_metaflow_get

        Get Account Metaflow List
        """
        pass

    def test_v1_account_account_id_metaflow_post(self) -> None:
        """Test case for v1_account_account_id_metaflow_post

        Create Account Metaflow
        """
        pass

    def test_v1_account_account_id_user_user_id_metaflow_delete(self) -> None:
        """Test case for v1_account_account_id_user_user_id_metaflow_delete

        Delete User Metaflow
        """
        pass

    def test_v1_account_account_id_user_user_id_metaflow_get(self) -> None:
        """Test case for v1_account_account_id_user_user_id_metaflow_get

        Get User Metaflow List
        """
        pass

    def test_v1_account_account_id_user_user_id_metaflow_post(self) -> None:
        """Test case for v1_account_account_id_user_user_id_metaflow_post

        Create User Metaflow
        """
        pass


if __name__ == '__main__':
    unittest.main()
