# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_docs_device_get_single import ServiceDocsDeviceGetSingle

class TestServiceDocsDeviceGetSingle(unittest.TestCase):
    """ServiceDocsDeviceGetSingle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceDocsDeviceGetSingle:
        """Test ServiceDocsDeviceGetSingle
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceDocsDeviceGetSingle`
        """
        model = ServiceDocsDeviceGetSingle()
        if include_optional:
            return ServiceDocsDeviceGetSingle(
                data = openapi_client.models.models/device_output_full.models.DeviceOutputFull(
                    call_forward = openapi_client.models.models/call_forward.models.CallForward(
                        enabled = True, 
                        number = '', ), 
                    call_recording = openapi_client.models.models/call_recording_settings.models.CallRecordingSettings(
                        any = openapi_client.models.models/call_recording_source.models.CallRecordingSource(
                            offnet = openapi_client.models.models/call_recording_parameters.models.CallRecordingParameters(
                                enabled = True, 
                                format = 'mp3', 
                                record_min_sec = 56, 
                                record_on_answer = True, 
                                record_on_bridge = True, 
                                record_sample_rate = 56, 
                                time_limit = 5, 
                                url = '', ), 
                            onnet = openapi_client.models.models/call_recording_parameters.models.CallRecordingParameters(
                                enabled = True, 
                                format = 'mp3', 
                                record_min_sec = 56, 
                                record_on_answer = True, 
                                record_on_bridge = True, 
                                record_sample_rate = 56, 
                                time_limit = 5, 
                                url = '', ), ), 
                        inbound = openapi_client.models.models/call_recording_source.models.CallRecordingSource(), 
                        outbound = , ), 
                    caller_id = openapi_client.models.models/device_output_full_callerid.models.DeviceOutputFullCallerid(
                        emergency = openapi_client.models.models/device_output_full_callerid_emergency.models.DeviceOutputFullCalleridEmergency(
                            number = '', ), 
                        external = openapi_client.models.models/device_output_full_callerid_external.models.DeviceOutputFullCalleridExternal(
                            number = '', ), 
                        internal = openapi_client.models.models/device_output_full_callerid_internal.models.DeviceOutputFullCalleridInternal(
                            number = '', ), ), 
                    device_type = '', 
                    do_not_disturb = openapi_client.models.models/voip_shared_do_not_disturb.models.VOIPSharedDoNotDisturb(
                        enabled = True, ), 
                    enabled = True, 
                    id = '', 
                    mac_address = '', 
                    media = openapi_client.models.models/device_output_full_media.models.DeviceOutputFullMedia(
                        audio = openapi_client.models.models/device_output_full_media_audio.models.DeviceOutputFullMediaAudio(
                            codecs = [
                                ''
                                ], ), ), 
                    music_on_hold = openapi_client.models.models/music_on_hold.models.MusicOnHold(
                        media_id = '', ), 
                    name = '', 
                    owner_id = '', 
                    provision = openapi_client.models.models/device_output_full_provision.models.DeviceOutputFullProvision(
                        endpoint_brand = '', 
                        endpoint_family = '', 
                        endpoint_model = '', 
                        id = '', 
                        line_keys = [
                            openapi_client.models.models/voip_device_output_line_key.models.VOIPDeviceOutputLineKey(
                                count = 56, 
                                label = '', 
                                type = '', 
                                value = '', )
                            ], ), 
                    sip = openapi_client.models.models/device_output_full_sip.models.DeviceOutputFullSIP(
                        invite_format = '', 
                        password = '', 
                        route = '', 
                        username = '', ), ),
                request_id = '',
                status_code = 56
            )
        else:
            return ServiceDocsDeviceGetSingle(
        )
        """

    def testServiceDocsDeviceGetSingle(self):
        """Test ServiceDocsDeviceGetSingle"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
