# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.models_user_output_full_callerid import ModelsUserOutputFullCallerid

class TestModelsUserOutputFullCallerid(unittest.TestCase):
    """ModelsUserOutputFullCallerid unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelsUserOutputFullCallerid:
        """Test ModelsUserOutputFullCallerid
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelsUserOutputFullCallerid`
        """
        model = ModelsUserOutputFullCallerid()
        if include_optional:
            return ModelsUserOutputFullCallerid(
                emergency = openapi_client.models.models/user_output_full_callerid_emergency.models.UserOutputFullCalleridEmergency(
                    number = '', ),
                external = openapi_client.models.models/user_output_full_callerid_external.models.UserOutputFullCalleridExternal(
                    number = '', ),
                internal = openapi_client.models.models/user_output_full_callerid_internal.models.UserOutputFullCalleridInternal(
                    number = '', )
            )
        else:
            return ModelsUserOutputFullCallerid(
        )
        """

    def testModelsUserOutputFullCallerid(self):
        """Test ModelsUserOutputFullCallerid"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
