# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_voip_account_limit2 import ServiceVOIPAccountLimit2

class TestServiceVOIPAccountLimit2(unittest.TestCase):
    """ServiceVOIPAccountLimit2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceVOIPAccountLimit2:
        """Test ServiceVOIPAccountLimit2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceVOIPAccountLimit2`
        """
        model = ServiceVOIPAccountLimit2()
        if include_optional:
            return ServiceVOIPAccountLimit2(
                inbound_trunks = 0,
                outbound_trunks = 0,
                twoway_trunks = 0
            )
        else:
            return ServiceVOIPAccountLimit2(
                inbound_trunks = 0,
                outbound_trunks = 0,
                twoway_trunks = 0,
        )
        """

    def testServiceVOIPAccountLimit2(self):
        """Test ServiceVOIPAccountLimit2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
