# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.models_user_output_full_callerid_external import ModelsUserOutputFullCalleridExternal

class TestModelsUserOutputFullCalleridExternal(unittest.TestCase):
    """ModelsUserOutputFullCalleridExternal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelsUserOutputFullCalleridExternal:
        """Test ModelsUserOutputFullCalleridExternal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelsUserOutputFullCalleridExternal`
        """
        model = ModelsUserOutputFullCalleridExternal()
        if include_optional:
            return ModelsUserOutputFullCalleridExternal(
                number = ''
            )
        else:
            return ModelsUserOutputFullCalleridExternal(
        )
        """

    def testModelsUserOutputFullCalleridExternal(self):
        """Test ModelsUserOutputFullCalleridExternal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
