# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_doc_group_get_all import ServiceDocGroupGetAll

class TestServiceDocGroupGetAll(unittest.TestCase):
    """ServiceDocGroupGetAll unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceDocGroupGetAll:
        """Test ServiceDocGroupGetAll
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceDocGroupGetAll`
        """
        model = ServiceDocGroupGetAll()
        if include_optional:
            return ServiceDocGroupGetAll(
                data = openapi_client.models.service/group_output_short.service.GroupOutputShort(
                    endpoints = 56, 
                    features = [
                        ''
                        ], 
                    flags = [
                        ''
                        ], 
                    group_endpoints = {
                        'key' : openapi_client.models.service/endpoint.service.Endpoint(
                            type = '', )
                        }, 
                    id = '', 
                    name = '', ),
                request_id = '',
                status_code = 56
            )
        else:
            return ServiceDocGroupGetAll(
        )
        """

    def testServiceDocGroupGetAll(self):
        """Test ServiceDocGroupGetAll"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
