# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_e911_location_uri_status import ServiceE911LocationURIStatus

class TestServiceE911LocationURIStatus(unittest.TestCase):
    """ServiceE911LocationURIStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceE911LocationURIStatus:
        """Test ServiceE911LocationURIStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceE911LocationURIStatus`
        """
        model = ServiceE911LocationURIStatus()
        if include_optional:
            return ServiceE911LocationURIStatus(
                code = '',
                description = ''
            )
        else:
            return ServiceE911LocationURIStatus(
        )
        """

    def testServiceE911LocationURIStatus(self):
        """Test ServiceE911LocationURIStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
