# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_e911_remove_location_status import ServiceE911RemoveLocationStatus

class TestServiceE911RemoveLocationStatus(unittest.TestCase):
    """ServiceE911RemoveLocationStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceE911RemoveLocationStatus:
        """Test ServiceE911RemoveLocationStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceE911RemoveLocationStatus`
        """
        model = ServiceE911RemoveLocationStatus()
        if include_optional:
            return ServiceE911RemoveLocationStatus(
                code = '',
                description = ''
            )
        else:
            return ServiceE911RemoveLocationStatus(
        )
        """

    def testServiceE911RemoveLocationStatus(self):
        """Test ServiceE911RemoveLocationStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
