# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.types_resource_record_set_region import TypesResourceRecordSetRegion

class TestTypesResourceRecordSetRegion(unittest.TestCase):
    """TypesResourceRecordSetRegion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypesResourceRecordSetRegion(self):
        """Test TypesResourceRecordSetRegion"""
        # inst = TypesResourceRecordSetRegion()

if __name__ == '__main__':
    unittest.main()
