# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_docs_device_get_all import ServiceDocsDeviceGetAll

class TestServiceDocsDeviceGetAll(unittest.TestCase):
    """ServiceDocsDeviceGetAll unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceDocsDeviceGetAll:
        """Test ServiceDocsDeviceGetAll
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceDocsDeviceGetAll`
        """
        model = ServiceDocsDeviceGetAll()
        if include_optional:
            return ServiceDocsDeviceGetAll(
                data = [
                    openapi_client.models.service/device_output_short.service.DeviceOutputShort(
                        device_type = '', 
                        do_not_disturb = openapi_client.models.models/voip_shared_do_not_disturb.models.VOIPSharedDoNotDisturb(
                            enabled = True, ), 
                        enabled = True, 
                        features = [
                            ''
                            ], 
                        flags = [
                            ''
                            ], 
                        id = '', 
                        name = '', 
                        owner_id = '', 
                        username = '', )
                    ],
                next_start_key = '',
                page_size = 56,
                request_id = '',
                start_key = '',
                status_code = 56
            )
        else:
            return ServiceDocsDeviceGetAll(
        )
        """

    def testServiceDocsDeviceGetAll(self):
        """Test ServiceDocsDeviceGetAll"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
