# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_voip_group_add_edit2 import ServiceVOIPGroupAddEdit2

class TestServiceVOIPGroupAddEdit2(unittest.TestCase):
    """ServiceVOIPGroupAddEdit2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceVOIPGroupAddEdit2:
        """Test ServiceVOIPGroupAddEdit2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceVOIPGroupAddEdit2`
        """
        model = ServiceVOIPGroupAddEdit2()
        if include_optional:
            return ServiceVOIPGroupAddEdit2(
                endpoints = {
                    'key' : openapi_client.models.service/endpoint.service.Endpoint(
                        type = '', )
                    },
                name = '0'
            )
        else:
            return ServiceVOIPGroupAddEdit2(
                endpoints = {
                    'key' : openapi_client.models.service/endpoint.service.Endpoint(
                        type = '', )
                    },
                name = '0',
        )
        """

    def testServiceVOIPGroupAddEdit2(self):
        """Test ServiceVOIPGroupAddEdit2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
