# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.phone_number_api import PhoneNumberApi


class TestPhoneNumberApi(unittest.TestCase):
    """PhoneNumberApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PhoneNumberApi()

    def tearDown(self) -> None:
        pass

    def test_v1_account_accountid_phonenumber_get(self) -> None:
        """Test case for v1_account_accountid_phonenumber_get

        Get Assigned Numbers List
        """
        pass

    def test_v1_account_phonenumber_assign_post(self) -> None:
        """Test case for v1_account_phonenumber_assign_post

        Assign Number
        """
        pass

    def test_v1_account_phonenumber_disconnect_post(self) -> None:
        """Test case for v1_account_phonenumber_disconnect_post

        Disconnect Number
        """
        pass

    def test_v1_account_phonenumber_get(self) -> None:
        """Test case for v1_account_phonenumber_get

        Get Unassigned Numbers List
        """
        pass

    def test_v1_account_phonenumber_post(self) -> None:
        """Test case for v1_account_phonenumber_post

        Purchase Number
        """
        pass

    def test_v1_account_phonenumber_unassign_post(self) -> None:
        """Test case for v1_account_phonenumber_unassign_post

        Unassign Number
        """
        pass

    def test_v1_phonenumber_search_get(self) -> None:
        """Test case for v1_phonenumber_search_get

        Search New Numbers
        """
        pass


if __name__ == '__main__':
    unittest.main()
