# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_metaflow_pattern import ServiceMetaflowPattern

class TestServiceMetaflowPattern(unittest.TestCase):
    """ServiceMetaflowPattern unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceMetaflowPattern:
        """Test ServiceMetaflowPattern
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceMetaflowPattern`
        """
        model = ServiceMetaflowPattern()
        if include_optional:
            return ServiceMetaflowPattern(
                children = {
                    'key' : openapi_client.models.service/metaflow_pattern.service.MetaflowPattern(
                        data = { }, 
                        module = 'transfer', )
                    },
                data = { },
                module = 'transfer'
            )
        else:
            return ServiceMetaflowPattern(
                module = 'transfer',
        )
        """

    def testServiceMetaflowPattern(self):
        """Test ServiceMetaflowPattern"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
