# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_system_status_messaging_service import ServiceSystemStatusMessagingService

class TestServiceSystemStatusMessagingService(unittest.TestCase):
    """ServiceSystemStatusMessagingService unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceSystemStatusMessagingService:
        """Test ServiceSystemStatusMessagingService
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceSystemStatusMessagingService`
        """
        model = ServiceSystemStatusMessagingService()
        if include_optional:
            return ServiceSystemStatusMessagingService(
                messaging_server = ''
            )
        else:
            return ServiceSystemStatusMessagingService(
        )
        """

    def testServiceSystemStatusMessagingService(self):
        """Test ServiceSystemStatusMessagingService"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
