# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.call_queue_management_api import CallQueueManagementApi


class TestCallQueueManagementApi(unittest.TestCase):
    """CallQueueManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CallQueueManagementApi()

    def tearDown(self) -> None:
        pass

    def test_v1_account_account_id_callqueue_get(self) -> None:
        """Test case for v1_account_account_id_callqueue_get

        Get Call Queues
        """
        pass

    def test_v1_account_account_id_callqueue_post(self) -> None:
        """Test case for v1_account_account_id_callqueue_post

        Create Call Queue
        """
        pass

    def test_v1_account_account_id_callqueue_queue_id_delete(self) -> None:
        """Test case for v1_account_account_id_callqueue_queue_id_delete

        Delete Call Queue
        """
        pass

    def test_v1_account_account_id_callqueue_queue_id_get(self) -> None:
        """Test case for v1_account_account_id_callqueue_queue_id_get

        Get Call Queue Details
        """
        pass

    def test_v1_account_account_id_callqueue_queue_id_put(self) -> None:
        """Test case for v1_account_account_id_callqueue_queue_id_put

        Update Call Queue
        """
        pass

    def test_v1_account_account_id_callqueue_queue_id_status_get(self) -> None:
        """Test case for v1_account_account_id_callqueue_queue_id_status_get

        Get Call Queue Status
        """
        pass

    def test_v1_account_account_id_queueroles_get(self) -> None:
        """Test case for v1_account_account_id_queueroles_get

        Get Queue Roles of Account
        """
        pass

    def test_v1_account_account_id_queueroles_queue_id_post(self) -> None:
        """Test case for v1_account_account_id_queueroles_queue_id_post

        Assign Queue Role to Call Queue
        """
        pass


if __name__ == '__main__':
    unittest.main()
