# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_voip_shared_do_not_disturb import ServiceVOIPSharedDoNotDisturb

class TestServiceVOIPSharedDoNotDisturb(unittest.TestCase):
    """ServiceVOIPSharedDoNotDisturb unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceVOIPSharedDoNotDisturb:
        """Test ServiceVOIPSharedDoNotDisturb
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceVOIPSharedDoNotDisturb`
        """
        model = ServiceVOIPSharedDoNotDisturb()
        if include_optional:
            return ServiceVOIPSharedDoNotDisturb(
                enabled = True
            )
        else:
            return ServiceVOIPSharedDoNotDisturb(
        )
        """

    def testServiceVOIPSharedDoNotDisturb(self):
        """Test ServiceVOIPSharedDoNotDisturb"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
