# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_e911_validate_location_input import ServiceE911ValidateLocationInput

class TestServiceE911ValidateLocationInput(unittest.TestCase):
    """ServiceE911ValidateLocationInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceE911ValidateLocationInput:
        """Test ServiceE911ValidateLocationInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceE911ValidateLocationInput`
        """
        model = ServiceE911ValidateLocationInput()
        if include_optional:
            return ServiceE911ValidateLocationInput(
                location = openapi_client.models.service/e911_location_input.service.E911LocationInput(
                    address_1 = '', 
                    address_2 = '', 
                    community = '', 
                    plus_four = '', 
                    postal_code = '', 
                    state = '', 
                    type = 'ADDRESS', )
            )
        else:
            return ServiceE911ValidateLocationInput(
                location = openapi_client.models.service/e911_location_input.service.E911LocationInput(
                    address_1 = '', 
                    address_2 = '', 
                    community = '', 
                    plus_four = '', 
                    postal_code = '', 
                    state = '', 
                    type = 'ADDRESS', ),
        )
        """

    def testServiceE911ValidateLocationInput(self):
        """Test ServiceE911ValidateLocationInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
