# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.types_alias_target import TypesAliasTarget

class TestTypesAliasTarget(unittest.TestCase):
    """TypesAliasTarget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TypesAliasTarget:
        """Test TypesAliasTarget
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TypesAliasTarget`
        """
        model = TypesAliasTarget()
        if include_optional:
            return TypesAliasTarget(
                dnsname = '',
                evaluate_target_health = True,
                hosted_zone_id = ''
            )
        else:
            return TypesAliasTarget(
        )
        """

    def testTypesAliasTarget(self):
        """Test TypesAliasTarget"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
