# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.types_rr_type import TypesRRType

class TestTypesRRType(unittest.TestCase):
    """TypesRRType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypesRRType(self):
        """Test TypesRRType"""
        # inst = TypesRRType()

if __name__ == '__main__':
    unittest.main()
