# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.provisioning_docs_docs_model_output import ProvisioningDocsDocsModelOutput

class TestProvisioningDocsDocsModelOutput(unittest.TestCase):
    """ProvisioningDocsDocsModelOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProvisioningDocsDocsModelOutput:
        """Test ProvisioningDocsDocsModelOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProvisioningDocsDocsModelOutput`
        """
        model = ProvisioningDocsDocsModelOutput()
        if include_optional:
            return ProvisioningDocsDocsModelOutput(
                data = [
                    openapi_client.models.models/model.models.Model(
                        brand_name = '', 
                        created_at = '', 
                        family_name = '', 
                        id = '', 
                        is_active = True, 
                        model_name = '', 
                        updated_at = '', )
                    ],
                next_start_key = '',
                page_size = 56,
                request_id = '',
                start_key = '',
                status_code = 56
            )
        else:
            return ProvisioningDocsDocsModelOutput(
        )
        """

    def testProvisioningDocsDocsModelOutput(self):
        """Test ProvisioningDocsDocsModelOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
