# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.system_status_api import SystemStatusApi


class TestSystemStatusApi(unittest.TestCase):
    """SystemStatusApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SystemStatusApi()

    def tearDown(self) -> None:
        pass

    def test_v1_ping_get(self) -> None:
        """Test case for v1_ping_get

        Ping Backend
        """
        pass

    def test_v1_pingseccognito_get(self) -> None:
        """Test case for v1_pingseccognito_get

        Ping Cognito
        """
        pass

    def test_v1_system_status_get(self) -> None:
        """Test case for v1_system_status_get

        Get System Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
