# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_doc_e911_active_location_output import ServiceDocE911ActiveLocationOutput

class TestServiceDocE911ActiveLocationOutput(unittest.TestCase):
    """ServiceDocE911ActiveLocationOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceDocE911ActiveLocationOutput:
        """Test ServiceDocE911ActiveLocationOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceDocE911ActiveLocationOutput`
        """
        model = ServiceDocE911ActiveLocationOutput()
        if include_optional:
            return ServiceDocE911ActiveLocationOutput(
                data = openapi_client.models.service/e911_active_location_output.service.E911ActiveLocationOutput(
                    location_status = openapi_client.models.service/e911_active_location_status.service.E911ActiveLocationStatus(
                        code = '', 
                        description = '', ), ),
                request_id = '',
                status_code = 56
            )
        else:
            return ServiceDocE911ActiveLocationOutput(
        )
        """

    def testServiceDocE911ActiveLocationOutput(self):
        """Test ServiceDocE911ActiveLocationOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
