# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_docs_admin_user_get_single import ServiceDocsAdminUserGetSingle

class TestServiceDocsAdminUserGetSingle(unittest.TestCase):
    """ServiceDocsAdminUserGetSingle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceDocsAdminUserGetSingle:
        """Test ServiceDocsAdminUserGetSingle
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceDocsAdminUserGetSingle`
        """
        model = ServiceDocsAdminUserGetSingle()
        if include_optional:
            return ServiceDocsAdminUserGetSingle(
                data = openapi_client.models.service/admin_user_output.service.AdminUserOutput(
                    email = '', 
                    first_name = '', 
                    id = 56, 
                    last_name = '', ),
                request_id = '',
                status_code = 56
            )
        else:
            return ServiceDocsAdminUserGetSingle(
        )
        """

    def testServiceDocsAdminUserGetSingle(self):
        """Test ServiceDocsAdminUserGetSingle"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
