# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.model_feature_daily_summary import ModelFeatureDailySummary

class TestModelFeatureDailySummary(unittest.TestCase):
    """ModelFeatureDailySummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelFeatureDailySummary:
        """Test ModelFeatureDailySummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelFeatureDailySummary`
        """
        model = ModelFeatureDailySummary()
        if include_optional:
            return ModelFeatureDailySummary(
                created_at = '',
                feature_count = 56,
                feature_name = '',
                log_date = ''
            )
        else:
            return ModelFeatureDailySummary(
        )
        """

    def testModelFeatureDailySummary(self):
        """Test ModelFeatureDailySummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
