# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_account_limit_output import ServiceAccountLimitOutput

class TestServiceAccountLimitOutput(unittest.TestCase):
    """ServiceAccountLimitOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceAccountLimitOutput:
        """Test ServiceAccountLimitOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceAccountLimitOutput`
        """
        model = ServiceAccountLimitOutput()
        if include_optional:
            return ServiceAccountLimitOutput(
                inbound_trunks = 56,
                outbound_trunks = 56,
                twoway_trunks = 56
            )
        else:
            return ServiceAccountLimitOutput(
        )
        """

    def testServiceAccountLimitOutput(self):
        """Test ServiceAccountLimitOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
