# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_temporal_rule_set_output_full import ServiceTemporalRuleSetOutputFull

class TestServiceTemporalRuleSetOutputFull(unittest.TestCase):
    """ServiceTemporalRuleSetOutputFull unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceTemporalRuleSetOutputFull:
        """Test ServiceTemporalRuleSetOutputFull
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceTemporalRuleSetOutputFull`
        """
        model = ServiceTemporalRuleSetOutputFull()
        if include_optional:
            return ServiceTemporalRuleSetOutputFull(
                id = '',
                name = '',
                temporal_rules = [
                    ''
                    ]
            )
        else:
            return ServiceTemporalRuleSetOutputFull(
        )
        """

    def testServiceTemporalRuleSetOutputFull(self):
        """Test ServiceTemporalRuleSetOutputFull"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
