# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.models_voip_device_output_line_key import ModelsVOIPDeviceOutputLineKey
from typing import Optional, Set
from typing_extensions import Self

class ModelsDeviceOutputFullProvision(BaseModel):
    """
    ModelsDeviceOutputFullProvision
    """ # noqa: E501
    endpoint_brand: Optional[StrictStr] = None
    endpoint_family: Optional[StrictStr] = None
    endpoint_model: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    line_keys: Optional[List[ModelsVOIPDeviceOutputLineKey]] = None
    __properties: ClassVar[List[str]] = ["endpoint_brand", "endpoint_family", "endpoint_model", "id", "line_keys"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelsDeviceOutputFullProvision from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in line_keys (list)
        _items = []
        if self.line_keys:
            for _item_line_keys in self.line_keys:
                if _item_line_keys:
                    _items.append(_item_line_keys.to_dict())
            _dict['line_keys'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelsDeviceOutputFullProvision from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "endpoint_brand": obj.get("endpoint_brand"),
            "endpoint_family": obj.get("endpoint_family"),
            "endpoint_model": obj.get("endpoint_model"),
            "id": obj.get("id"),
            "line_keys": [ModelsVOIPDeviceOutputLineKey.from_dict(_item) for _item in obj["line_keys"]] if obj.get("line_keys") is not None else None
        })
        return _obj


