# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.service_campaign_import_output_mno_status_list_inner import ServiceCampaignImportOutputMnoStatusListInner
from typing import Optional, Set
from typing_extensions import Self

class ServiceCampaignImportOutput(BaseModel):
    """
    ServiceCampaignImportOutput
    """ # noqa: E501
    campaign_id: Optional[StrictStr] = None
    created_date: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    message_class: Optional[StrictStr] = None
    mno_status_list: Optional[List[ServiceCampaignImportOutputMnoStatusListInner]] = None
    secondary_dca_sharing_status: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["campaign_id", "created_date", "description", "message_class", "mno_status_list", "secondary_dca_sharing_status", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServiceCampaignImportOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in mno_status_list (list)
        _items = []
        if self.mno_status_list:
            for _item_mno_status_list in self.mno_status_list:
                if _item_mno_status_list:
                    _items.append(_item_mno_status_list.to_dict())
            _dict['mno_status_list'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServiceCampaignImportOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "campaign_id": obj.get("campaign_id"),
            "created_date": obj.get("created_date"),
            "description": obj.get("description"),
            "message_class": obj.get("message_class"),
            "mno_status_list": [ServiceCampaignImportOutputMnoStatusListInner.from_dict(_item) for _item in obj["mno_status_list"]] if obj.get("mno_status_list") is not None else None,
            "secondary_dca_sharing_status": obj.get("secondary_dca_sharing_status"),
            "status": obj.get("status")
        })
        return _obj


