# coding: utf-8

"""
    White Label Communications CPaas API Documentation

    A CPaaS platform API

    The version of the OpenAPI document: 1.1
    Contact: support@whitelabelcomm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TypesRRType(str, Enum):
    """
    TypesRRType
    """

    """
    allowed enum values
    """
    RRTypeSoa = 'SOA'
    RRTypeA = 'A'
    RRTypeTxt = 'TXT'
    RRTypeNs = 'NS'
    RRTypeCname = 'CNAME'
    RRTypeMx = 'MX'
    RRTypeNaptr = 'NAPTR'
    RRTypePtr = 'PTR'
    RRTypeSrv = 'SRV'
    RRTypeSpf = 'SPF'
    RRTypeAaaa = 'AAAA'
    RRTypeCaa = 'CAA'
    RRTypeDs = 'DS'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TypesRRType from a JSON string"""
        return cls(json.loads(json_str))


